---
title: "Instacart Exploratory Analysis"
output: html_notebook
---


```{r}
source("readDataToMemory.R")
read_instacart()

library(DBI)
library(ggplot2)
library(ggthemes)

src_tbls(sc)
```

### Order products

`order_products__*.csv`

These files specify which products were purchased in each order.

```{r}
dbGetQuery(sc, "SELECT * FROM order_products__prior_tbl LIMIT 10")
```
 
 
 
```{r}
dbGetQuery(
  sc,
  "
SELECT COUNT(DISTINCT product_id) AS products
FROM order_products__prior_tbl
  "
  )
```

```{r}
products_popularity_txt <- "
SELECT product_id
,   COUNT(1) AS n_orders
FROM order_products__prior_tbl
GROUP BY product_id
ORDER BY n_orders DESC
LIMIT 50
"

products_popularity <-
  dbGetQuery(sc, products_popularity_txt)

products_popularity
```

## Products

`products.csv`

```{r}
dbGetQuery(sc, "SELECT * FROM products_tbl LIMIT 20")
```

```{r}
products_popularity_txt <- "
SELECT op.product_id
,   n_orders
,   product_name
FROM (
    SELECT product_id
    ,   COUNT(1) AS n_orders
    FROM order_products__prior_tbl
    GROUP BY product_id
    ORDER BY n_orders DESC
    LIMIT 30) op
LEFT JOIN (
    SELECT product_id
    ,   product_name
    FROM products_tbl) p
ON op.product_id = p.product_id
"

products_popularity <-
  dbGetQuery(sc, products_popularity_txt)

##

products_popularity %>%
  ggplot(
    aes(reorder(product_name, n_orders, function(x) x), 
        n_orders)) +
  geom_bar(stat="identity", fill='darkorange') +
  coord_flip() + 
  scale_y_continuous(label=scales::comma) +
  xlab("product") +
  ylab("Number of orders") +
  theme_minimal()

```


## Orders

`orders.csv`

This file tells to which set (prior, train, test) an order belongs. 


```{r}
orders_prev <- dbGetQuery(sc, "SELECT * FROM orders_tbl LIMIT 100")
orders_prev
```

```{r}
dbGetQuery(sc, 
"
SELECT days_since_prior_order
,   COUNT(1) AS N
FROM orders_tbl
GROUP BY days_since_prior_order
") 
```


```{r}
dbGetQuery(sc, 
"SELECT * 
FROM orders_tbl
WHERE user_id <= 10
")
```
```{r}
dbGetQuery(sc, 
"SELECT user_id
,   order_id
,   FIRST_VALUE(order_id)  OVER(partition by user_id ORDER BY order_number) AS first_order
FROM orders_tbl
WHERE user_id <= 10 
")
```

