---
title: "Big Data Management"
subtitle: "with R (Day 2)"
author: "Bartek Skorulski"
date: "June 27, 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# What we have done so far

##

* We were discussing what is `Big Data Management` and what is the role of `Data Scientist` in it.
* We were discussing what tools we can use and how they integrate with toolbox of `R Data Scientist`.
* We forked and cloned git respository.
* We did Hive-like queries. 
* We have even found some problems, but have not found Data Engineer to help us. 

# Plan for today

##

* Git (30 min)
    - We do push out git repo and request pull from upstream repo.
    - We configure upstream repo and pull code from there.
* SQL/dplyr 
    - Finishing previous exercise. (30 min)
    - We will compare SQL and dplyr. (45 min)
    - We will learn about window functions. (45 min)
    - We will learn about whisker. (30 min)
    - We will discuss what kind of big questions we ask about Instacart Data, what
    actions we can propose and how we could possible design experiment in order to 
    test them.

# Exercise 1: push and pull...

## Push and pull request

* See your changes
```
git status
```
Make sure you are not going to commit big files
* Stage and commit changes
```
git add -A
git commit -m "finishes day 1 activites"
```
* Push
```
git push origin master
```
* Request pull

## Pull from upstream

* Configure upstream
```
git remote add upstream https://github.com/sbartek/big_data_with_R
```
* Fetch upstream
```
git fetch upstream
git checkout master
git merge upstream/master
```

# Finishig previous exercise

# Exercise 2: SQL vs dlyr

